# ---------------------------------------------------------------
# ⚠ Attention!
# ---------------------------------------------------------------
# Hexo There are two configuration files, namely the "site configuration file" 
# located in the site root directory and the "theme configuration file" here
# Pay attention to the corresponding configuration file when modifying, 
# some of the content of the theme configuration file may need to be copied 
# to the site configuration file to take effect



# ---------------------------------------------------------------
# <head> Label configuration
# ---------------------------------------------------------------

head: 
# Website icon
  favicon: /favicon.ico
# Social sharing links
  opengraph: 
    enable: true
    type: 
    twitter_card: summary_large_image
    twitter_id: 
    twitter_site: 
    image: page.thumbnail
    fb_admins: 
    fb_app_id: 

# Custom head
  custom_head: 
    # - ''
    # - ''



# ---------------------------------------------------------------
# Navigation bar/cover configuration
# ---------------------------------------------------------------

# Top navigation bar settings
navbar: 

  # Name display on the left
  sitename: Natural Scholar
  
  # Navigation link in the station on the right
  menu: 
    # - name: Stories
    #   url: /categories/
    # - name: Events
    #   url: /categories/
    # - name: Food
    #   url: /categories/
    # - name: Art
    #   url: /categories/

# The navigation bar is always displayed at the top of the screen
# Only effective when the screen width is not less than 1080 px
  sticky: true

# Cover settings
cover: 

  # The site name displayed at the top cover
  sitename: Natural Scholar

  # If the logo is set, the logo will be used first instead of sitename
  logo: 
  
  # logo below a sentence introduction
  description: A Research Project


# ---------------------------------------------------------------
# Style customization
# ---------------------------------------------------------------

style: 

  # Color configuration
  color: 
    main_color: '#eb5757'

  # Radian setting
  radius: 
    main_radius: 5px
    
  # Spacing setting
  space: 
    main_space: 3.5rem
    sm_space: 1.5rem  # 当屏幕宽度小于 650px 时候启用

  # Default code highlight
  highlight: 

    # Default code highlight theme
    default: 

    # Dark code highlight theme
    darkmode: 

  # highlight.js code highlighting
  hljs: 

    # Default code highlight theme
    default: 

    # Dark code highlight theme
    darkmode: 

  # prismjs code highlighting
  prismjs: 

    # Default code highlight theme
    default: 

    # Dark code highlight theme
    darkmode: 



# ---------------------------------------------------------------
# meta library
# ---------------------------------------------------------------

meta:

  # Default article title
  title: 'no title'
  
  # Default article author (can be overridden in front-matter)
  author:
    name: admin@naturalscholar.com
    url: https://www.naturalscholar.com
  
  # Article creation date
  date:
    title: ''
    format: 'YYYY-MM-DD' # Date format http://momentjs.com/docs/
  
  # Article update date
  updated:
    title: ''
    format: 'YYYY-MM-DD' # Date format http://momentjs.com/docs/

  # Article thumbnail
  thumbnail: 
    enable: false
    default: https://res.cloudinary.com/alchemist-cookbook/image/upload/v1538465246/favicon.png  # Default thumbnail, when the page `thumbnail` field is empty, fallback to this parameter

  # Article outdated reminder
  expire: 
    enable: false
    duration: 120  # Over this number of days will display an overdue reminder

  # Article automatic summary
  auto_excerpt: 
    enable: true
    length: 150

  # Article Directory
  toc: 
    enable: true
    list_number: false

  # Article copyright statement
  copyright: 
    enable: true
    
    # After the author's statement and permanent link, it can be multiple lines, support markdown
    custom_text:
      - 'Thank you for your support!'
      - 'BTC: bc1qx6pkaaszg66x3tcpgt5zd6x0pszdwy0sa3sv3n'



# ---------------------------------------------------------------
# Comment system
# ---------------------------------------------------------------

comments: 
  use:   # disqus | disqusjs | valine | minivaline | gitalk | gitment | levere | changyan | wildfire

  ## Disqus
  disqus:  
    shortname: 

  ## DisqusJS  
  disqusjs: 
    shortname: 
    siteName: 
    api: 
    apikey: 
    admin: ''
    nesting: 2

  ## Valine
  valine: 
    appId: 
    appKey:
    placeholder: 
    path: 
    avatar: 
    meta: [nick, mail, link]
    pageSize: 
    lang: 
    visitor: 
    highlight: 
    avatarForce: 
    recordIP: 
    serverURLs: 
    enableQQ: 
    requiredFields: [nick, mail]
    emojiCDN: 
    emojiMaps: 

  # MiniValine
  minivaline:  
    appId: 
    appKey: 
    mode: 
    placeholder: 
    pathname: 
    adminEmailMd5: 
    master: 
    friends: 
    tagMeta: 
    math: 
    md: 
    lang: 
    emoticonUrl:
    NoRecordIP: 
    maxNest: 
    pageSize: 
    enableQQ: 
    visitor: 
    serverURLs: 

  ## Gitalk
  gitalk:
    repo:
    owner:
    clientID:
    clientSecret:

  ## Gitment
  gitment:
    repo:
    owner:
    client_id:
    client_secret:
  
  # Livere Come to compare
  livere: 
    livere_uid:

  # Speak freely
  changyan: 
    appid:
    conf:
    thread_key_type: path # id | path，use "id" when defining separately
  wildfire: 
    database_provider: firebase # firebase | wilddog
    wilddog_site_id:
    firebase_api_key:
    firebase_auth_domain:
    firebase_database_url:
    firebase_project_id:
    firebase_storage_bucket:
    firebase_messaging_sender_id:
    theme: dark # light | dark
    locale: en



# ---------------------------------------------------------------
# Statistics Service
# ---------------------------------------------------------------

analytics:
  google_site_id:
  gtags_site_id:
  baidu_site_id: 
  cnzz_site_id: 



# ---------------------------------------------------------------
#  Site footer
# ---------------------------------------------------------------

footer:
  
  # Set the start time of the site for the bottom copyright display
  # For example: Set this to `2018`, then the footer will display'© 2018-2020' (2020 is the last page generation time)
  # If you leave this item blank,'© 2020' will be displayed separately (2020 is the last page generation time)
  # If you do not want to display any content, please set this to `false`
  copyright_since: 

  #  Site count
  statistics: 

    # Select LeanCloud/busuanzi as the website count. If you don’t want to enable it at all, just leave the `use` item blank.
    use:   # leancloud | busuanzi

    # If you choose to use LeanCloud, you need to complete the following configuration items
    leancloud: 
      appId: 
      appKey: 
      serverURL:   # REST API server address, not for LeanCloud international version

    # Site-wide UV （Unique Viewers）
    site_uv:
      enable: true
      before_text: '' # Display the content before the data, support HTML
      after_text: Viewers  # Display the content behind the data, support HTML
      divider: '&nbsp;&nbsp;&nbsp;|' # Separator, HTML syntax support
    
    # Total station PV（Page Views）
    site_pv:
      enable: true
      before_text: ''  # 展示在数据前的内容，支持 HTML
      after_text: Views  # 展示在数据后的内容，支持 HTML
      divider: ''  # 分隔符，HTML 语法支持
    
    # Page PV
    page_pv:
      enable: true
      before_text: ''
      after_text: Views 

  # Custom footer, support markdown
  custom_text: 
    # - 'Donate'
    # - 'BTC:'



# ---------------------------------------------------------------
# Optimization/function plugin
# ---------------------------------------------------------------

# Image lazy loading plugin
# You need to move the `lazyload` configuration item to the site 
# configuration file to make the relevant configuration effective! ! !
lazyload:
  enable: false
  onlypost: false
  loadingImage: 

# Site search plugin
# You need to move the `search` configuration item to the site configuration file to 
# make the relevant configuration effective! ! !
search:
  enable: false
  path: search.json
  field: All  # Page | Post | All

# note tag plugin
note: false

# Picture click to enlarge plugin
fancybox: 
  enable: true
  auto: true
  
# Back to top
back_to_top: false

# Dark Mode
darkmode: true



# ---------------------------------------------------------------
# CDN for vendors
# ---------------------------------------------------------------

# Vendors
# Leave an item blank to call the default/local file
vendors:

  # main style css
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.0/dist/css/style/main.min.css
  # Version: 1.0
  # If you have a custom style, please be sure to modify this item to your CDN address, or simply leave it blank
  style: 

  # darkmode
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.0/dist/css/style/dark.min.css
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.0/dist/js/darkmode.min.js
  # Version 1.0
  darkmode: 
    css: 
    js: 
  
  # code highlight css
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.0/dist/css/highlight/
  # Version: 1.0
  highlight: 

  # highlight.js theme
  # https://cdn.jsdelivr.net/npm/highlight.js@10.1.2/styles/
  # Version: 10.1.2
  hljs: 

  # prism.js theme
  # https://cdn.jsdelivr.net/npm/prismjs@1.21.0/themes/
  # Version: 1.21.0
  prism: 

  # tag-plugin note css
  # https://github.com/ChrAlpha/hexo-theme-cards
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.0/dist/css/style/note.min.css
  # Version 1.0
  note: 

  # Lazyload js
  # https://github.com/verlok/lazyload
  # Version: 17.1.0
  lazyload: 
  
  # back_to_top button
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.0/dist/js/b2t.min.js
  # Version 1.0
  back_to_top: 

  # local search plugin
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.0/dist/js/local-search.min.js
  # Version 1.0
  local_search: 
  
  # Valine comments system
  # https://github.com/xcss/Valine/
  # Version: 1.4.14
  valine: 

  # MiniValine
  # https://github.com/MiniValine/MiniValine
  # Version 2.7.5
  minivaline: 
  
  # Wildfire comments system
  # https://github.com/cheng-kang/wildfire/
  # Version: 0.3.9
  wildfire: 
  
  # MathJax js
  # https://www.mathjax.org/
  # Version: 3
  mathjax: 

  # busuanzi counter js
  # https://busuanzi.ibruce.info
  busuanzi: 
  
  # jQuery js
  # https://github.com/jquery/jquery/
  # Version: 3.4.1
  jquery: 
  
  # fancybox css
  # https://github.com/fancyapps/fancybox/
  # Version: 3.5.7
  fancybox: 
    css: 
    js: 

  # Custom script
  custom_script: 
    # - ''
    # - ''


